// Generated by https://quicktype.io

export type PokemonResponse = {
  count: number;
  next: string;
  previous: null | string;
  results: PokemonResult[];
};

export type PokemonResult = {
  name: string;
  url: string;
};
