// Generated by https://quicktype.io

import {IPokemon} from './pokemon';

export type PokemonListResponse = {
  count: number;
  next: string;
  previous: null | string;
  results: PokemonResult[];
};

export type PokemonResult = {
  name: string;
  url: string;
};

export type PokemonDetailRespose = {
  id: number;
  name: string;
  abilities: PokemonDetailAbilityResponse[];
  height: number;
  weight: number;
  stats: PokemonDetailStatResponse[];
  types: PokemonDetailTypeResponse[];
};

export type PokemonDetailStatResponse = {
  base_stat: number;
  effort: number;
  stat: {
    name: string;
    url: string;
  };
};

export type PokemonDetailTypeResponse = {
  slot: number;
  type: {
    name: string;
    url: string;
  };
};

export type PokemonDetailAbilityResponse = {
  ability: {
    name: string;
    url: string;
  };
  is_hidden: boolean;
  slot: number;
};

export type PokemonListResponseAddated = {
  meta: {count: number; nextPage: string};
  results: IPokemon[];
};
